#!/bin/sh

echo "\documentclass[a4paper]{article}" > make.tex
echo "\usepackage{graphicx,bm,amsmath}" >> make.tex
echo "\pagestyle{empty}" >> make.tex

echo "\begin{document}" >> make.tex
echo "\begin{figure}[htbp]" >> make.tex
echo "\input{$1}" >> make.tex
echo "\end{figure}" >> make.tex
echo "\end{document}" >> make.tex

latex make.tex
rm -rf make.aux
dvips make.dvi
rm -rf make.dvi
ps2eps -f make.ps
rm -rf make.ps
eps2eps make.eps Fig.eps
rm -rf make.tex make.eps
rm -rf *.log

